Softuni Project/Models/TextPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Softuni_Project.Models
{
    public class TextPost
    {
        private ICollection<Comment> comments;

        public TextPost()
        {
            Comments = new HashSet<Comment>();
            DatePosted = DateTime.Now;
            UsersLikesIDs = String.Empty;

        }
        public TextPost(string authorId, string title, string content, int categoryId)
        {
            this.AuthorId = authorId;
            this.Title = title;
            this.Content = content;
            this.CategoryId = categoryId;
            this.comments = new HashSet<Comment>();
            UsersLikesIDs = String.Empty;
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public int Score { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string UsersLikesIDs { get; set; }

        public DateTime DatePosted { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public virtual ICollection<Comment> Comments
        {
            get { return this.comments; }
            set { this.comments = value; }
        }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public bool IsAuthor(string name)
        {
            return this.Author.UserName.Equals(name);
        }

    }
}

Softuni Project/Models/TextPostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Softuni_Project.Models
{
    public class TextPostViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [DisplayName("Post")]
        public string Content { get; set; }

        public string AuthorId { get; set; }

        [ForeignKey("Category")]
        [DisplayName("Category")]
        [Required]
        public int CategoryId { get; set; }

        public List<Category> Categories { get; set; }

        public int Score { get; set; }

       

      


    }
}

Softuni Project/Controllers/TextPostController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Softuni_Project.Models;
using Microsoft.AspNet.Identity;
using Softuni_Project.Extensions;

namespace Softuni_Project.Controllers
{
    public class TextPostController : Controller
    {
        // GET: TextPost
        public ActionResult Index()
        {


            return RedirectToAction("ListAll");

        }


        public ActionResult ListAll(string sortOrder, int? id)
        {
          
            ViewBag.TitleSortParm = "name_order";
            ViewBag.ScoreSortParm = "score_order";
            ViewBag.DateSortParm = "new_posts_first";
            using (var db = new BlogDbContext())
            {
                var posts = db.TextPosts.
                     Include(a => a.Author);
                     
                switch (sortOrder)
                {
                  
                    case "new_posts_first":
                       posts = posts.OrderByDescending(s => s.DatePosted);
                        
                        break;
                    case "name_order":
                        posts= posts.OrderBy(s => s.Title);
                        break;
 
                    case "score_order":
                      posts  = posts.OrderByDescending(s => s.Score);
                        break;
                    default:
                        posts = posts.OrderBy(s => s.DatePosted);
                        break;
                }
               

                var dbCategories = db.Categories.ToList();
                Dictionary<int,string> categories = new Dictionary<int, string>();

                foreach (var category in dbCategories)
                {
                    categories[category.Id] = category.Name;

                }

                ViewBag.Categories = categories;

                if (id != null)
                {
                    //The user clicked on a category, show only the posts in the same one

                    var categoryPosts = db.TextPosts.Where(t => t.CategoryId == id).Include(a => a.Author);

                    ViewBag.TitleSortParm = "name_order";
                    ViewBag.ScoreSortParm = "score_order";
                    ViewBag.DateSortParm = "new_posts_first";

                    switch (sortOrder)
                    {

                        case "new_posts_first":
                            categoryPosts = categoryPosts.OrderByDescending(s => s.DatePosted);

                            break;
                        case "name_order":
                            categoryPosts = categoryPosts.OrderBy(s => s.Title);
                            break;

                        case "score_order":
                            categoryPosts = categoryPosts.OrderByDescending(s => s.Score);
                            break;
                        default:
                            categoryPosts = categoryPosts.OrderBy(s => s.DatePosted);
                            break;
                    }



                    return View(categoryPosts.ToList());
                }


                return View(posts.ToList());

            } 
           
        }


        public bool IsUserAuthorizedToEdit(TextPost textpost)
        {
            
            bool IsAdmin = this.User.IsInRole("Admin");
            bool IsAuthor = textpost.IsAuthor(this.User.Identity.Name);
            return IsAdmin || IsAuthor;
        }
        //
        // GET: TextPost/Details
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {

                var article = database.TextPosts
                    .Where(p => p.Id == id)
                    .Include(p => p.Author)
                    .Include(p => p.Comments.Select(c => c.Author))
                    .First();

                if (article == null)
                {
                    return HttpNotFound();
                }

                return View(article);
            }
        }
      
        [Authorize]
        public ActionResult Create()
        {
            //check if we have error messages from our last attempt to create a post
            if (TempData["message"] != null)
            {
                ViewBag.Message = TempData["message"].ToString();
            }


            using (var databse = new BlogDbContext())
            {
                var model = new TextPostViewModel();
                model.Categories= databse.Categories
                    .OrderBy(c => c.Name)
                    .ToList();
                return View(model);
            }
                
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(TextPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new BlogDbContext())
                {
                    var authorId = db.Users.Where(u => u.UserName == this.User.Identity.Name).First().Id;
                    var textPost = new TextPost(authorId, model.Title, model.Content, model.CategoryId);

                    textPost.DatePosted = DateTime.Now;
                    db.TextPosts.Add(textPost);
                    db.SaveChanges();

                    this.AddNotification("You have successfully created a Post.", NotificationType.SUCCESS);
                    TempData["message"] = null;
                    return RedirectToAction("Index");

                }

            }
            else
            {
                //the create process failed, this message will be displayed 
                TempData["message"] = "Please make sure the title and the content of your post are not empty.";
                return RedirectToAction("Create");

            }
            return View(model);

        }

        //
        // GET: TextPost/Edit
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var database = new BlogDbContext())
            {
                var textPost = database.TextPosts
                    .Where(a => a.Id == id)
                    .First();
                if (textPost == null)
                {
                    return HttpNotFound();
                }
                var model = new TextPostViewModel();
                model.Id = textPost.Id;
                model.Title = textPost.Title;
                model.Content = textPost.Content;
                model.CategoryId = textPost.CategoryId;
                model.Categories = database.Categories
                    .OrderBy(c => c.Name)
                    .ToList();


                return View(model);
            }
        }
        //
        //POST: TextPost/Edit
        [HttpPost]
        [Authorize]
        [ActionName("Edit")]
        public ActionResult Edit(TextPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
                    var textPost = database.TextPosts
                        .FirstOrDefault(a => a.Id == model.Id);
                    if (!IsUserAuthorizedToEdit(textPost))
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                    }
                    textPost.Title = model.Title;
                    textPost.Content = model.Content;
                    textPost.CategoryId = model.CategoryId;


                    database.Entry(textPost).State = EntityState.Modified;
                    database.SaveChanges();
                    this.AddNotification("You have successfully edited your Post.", NotificationType.SUCCESS);

                    return RedirectToAction("Index");

                }
            }
            return View(model);
        }
        //
        // GET: TextPost/Delete
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var database = new BlogDbContext())
            {
                var textPost = database.TextPosts
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .Include(c=>c.Category)
                    .First();
                if (textPost == null)
                {
                    return HttpNotFound();
                }
                return View(textPost);
            }
        }

        //
        //POST: TextPost/Delete
        [HttpPost]
        [Authorize]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var database = new BlogDbContext())
            {
                var textPost = database.TextPosts
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();
                if (!IsUserAuthorizedToEdit(textPost))
                {

                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }


                if (textPost== null)
                {
                    return HttpNotFound();
                }

                database.TextPosts.Remove(textPost);
                database.SaveChanges();
                this.AddNotification("Post deleted.", NotificationType.INFO);

                return RedirectToAction("Index");

            }
        }

        [HttpPost]
        [Authorize]

Softuni Project/Views/TextPost/Create.cshtml
@model Softuni_Project.Models.TextPostViewModel
@{
    ViewBag.Title = "Create";
}
@Styles.Render("~/Content/CreateTextPost.css")

<div class="container">
    <div class="row"><h2 class="text-center blueColor"><span class="glyphicon glyphicon-pencil blackColor"></span> Create Post</h2></div>
        
        @if (ViewBag.Message != null)
        {
            <div class="alert-danger" style="padding: 10px">@ViewBag.Message</div>
        }

        @using (Html.BeginForm("Create", "TextPost", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "8" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CategoryId, new {@class = "col-sm-4 control-label"})
                <div class="dropdown col-sm-4">
                    @Html.DropDownListFor(m => m.CategoryId,
                        new SelectList(Model.Categories, "Id", "Name"),
                        new {@class = "btn btn-info col-sm-12"})
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "TextPost", null, new { @class = "btn btn-default marginLeft" })
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        }
</div>

Softuni Project/Views/TextPost/Delete.cshtml
@model Softuni_Project.Models.TextPost

@{
    ViewBag.Title = "Delete";
}
@Styles.Render("~/Content/EditDeleteTextPost.css")

<div class="container">
        <div class="row col-md-offset-4"><h2><span class="glyphicon glyphicon-remove"></span> <span class="colorRed">Delete Post</span></h2></div>
    <div class="row">

        @using (Html.BeginForm("Delete", "TextPost", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Category.Name, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "TextPost", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        }

    </div>
</div>

Softuni Project/Views/TextPost/Details.cshtml
@model Softuni_Project.Models.TextPost
@{
    ViewBag.Title = "Details";
}

<head>
    <link href="~/Content/TextPost.css" rel="stylesheet" type="text/css" />
</head>
@Styles.Render("~/Content/TextPost.css")


<div class="container">
    <!--Article Title / Content / Author-->

    <div class="row">
        <div class="col-sm-12 text-center">
            <header>
                <h1>
                    @Html.ActionLink(Model.Title, "Details", "TextPost", new { @id = Model.Id }, new { style = "text-decoration:none;font-size:41px;" })
                </h1>
            </header>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12" id="mainContent">
            <article>
                @Model.Content
            </article>
        </div>
        <div class="pull-right">
            <p>submitted by: <span class="authorAndScore">@Model.Author.FullName</span>, score <span class="authorAndScore">@Model.Score</span></p>
        </div>
    </div>

    <!-- Edit Delete Back Buttons-->
    <div class="row">
        <div class="text-center">
            @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name))
            {
                @Html.ActionLink("Edit", "Edit", "TextPost", new { @id = Model.Id }, new { @class = "btn btn-success btn-xs postConfigButton" })
                @Html.ActionLink("Delete", "Delete", "TextPost", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs postConfigButton" })
            }
            @Html.ActionLink("Back", "ListAll", "TextPost", null, new { @class = "btn btn-default btn-xs textPostBtn" })
        </div>
    </div>


    <!-- Comment Form -->
    @if (User.Identity.IsAuthenticated)
    {
        <div class="row">
            <div class="col-sm-3">
                <h2 class="blueHeading">Comment here:</h2>
            </div>
            <div class="col-sm-7">
                @using (Ajax.BeginForm("PostComment", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "Comments", OnFailure = "commentPostFailure" }))
                {

                    @Html.Hidden("TextPostId", Model.Id)
                    @Html.TextArea("Content", "")
                    @Html.AntiForgeryToken()
                <div class="col-sm-offset-5"><input type="submit" value="Comment" class="btn btn-default commentButton text-center" /></div>

                }                
            </div>                         
        </div>        
    }


    <!-- Comments -->
    <div class="row">
        <div class="col-sm-3">
        </div>
        @foreach (var comment in Model.Comments)
        {
            @Html.Partial("_CommentPartial", comment)

        }
    </div>
</div>

Softuni Project/Views/TextPost/Edit.cshtml
@model Softuni_Project.Models.TextPostViewModel
@{
    ViewBag.Title = "Edit";
}
@Styles.Render("~/Content/EditDeleteTextPost.css")

<div class="container">
    <div class="row col-md-offset-4"><h2><span class="glyphicon glyphicon-pencil"></span> <span class="colorBlue">Edit Post</span></h2></div>
        
    <div class="row">

        @using (Html.BeginForm("Edit", "TextPost", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CategoryId, new { @class = "control-label col-sm-4" })
                <div class="dropdown col-sm-4">
                    @Html.DropDownListFor(m => m.CategoryId,
                        new SelectList(Model.Categories, "Id", "Name", Model.CategoryId),
                        new { @class = "btn btn-info col-sm-12" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "TextPost", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-success" />
                </div>
            </div>
        }

    </div>
</div>

Softuni Project/Views/TextPost/ListAll.cshtml
@model List<Softuni_Project.Models.TextPost>
@{
    ViewBag.Title = "Posts";
}
@Styles.Render("~/Content/ListAllIndex.css")
<div class="container">
    <div class="row" style="margin-top:15px;">
        <div class="col-sm-offset-3 col-sm-9 text-center" id="sortBy">
            @Html.ActionLink("Title", "ListAll", new { sortOrder = ViewBag.TitleSortParm })
            @Html.ActionLink("Score", "ListAll", new { sortOrder = ViewBag.ScoreSortParm })
            @Html.ActionLink("Date Posted", "ListALL", new { sortOrder = ViewBag.DateSortParm })
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-3" id="categoriesList">
            <h3 class="categoriesHeading text-center">Categories:</h3>

            @foreach (var c in ViewBag.Categories)
            {
                <div class="alert alert-info">
                   
                    @{
                        string categoryName = c.Value;
                        @Html.ActionLink(categoryName, "ListAll", "TextPost", new {@id = c.Key},null);
                    }

                </div>
            }
        </div>
        <div class="col-sm-9" id="allPosts">
            @foreach (var post in Model)
            {
                <div class="col-sm-12 text-center currentPost">
                    <article>
                        <header>
                            <h2>
                                @Html.ActionLink(@post.Title, "Details", "TextPost", new { @id = post.Id }, null)
                            </h2>
                        </header>
                        <footer class="pull-left col-sm-12">
                            <p>submitted by @post.Author.FullName , score @post.Score</p>
                        </footer>
                    </article>
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LikePost", "TextPost", new { @id = post.Id }, FormMethod.Post))
                        {
                            <button type="submit" class="btn btn-primary"> <span class="glyphicon glyphicon-thumbs-up thumbs-up"></span> </button>
                        }
                    }
                </div>
                <hr />
            }
        </div>
    </div>
</div>